# Generated by Django 3.0.8 on 2020-07-28 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20200725_1250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='digital',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('electronic-devices', 'electronic-devices'), ('apparel', 'apparel'), ('personal-appliance', 'personal-appliance'), ('home', 'home'), ('book-and-media', 'book-and-media'), ('others', 'others')], default='others', max_length=20),
        ),
    ]
