# Generated by Django 3.0.8 on 2020-08-01 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20200728_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='D:\\Dev\\ecommerce\\ecommerce\\static/images'),
        ),
    ]
